### ISSUE TITLE
Tab key selection event in dropdown components

### ISSUE THREAD

**Issue by vpanag** [orangehrm/oxd#796]
When a dropdown component gets focus it opens, user can move up/down with arrow keys and:
- if user presses enter, selected option updates the model, all OK.
- if user presses TAB key, dropdown changes selected option in UI, focus moves to next field but the model never gets updated.
In this case, user sees a value in dropdown not corresponding to internal model value.
Tested with components defined as:
```
<template>
  <oxd-input-field type="select" :options="options"> </oxd-input-field>
</template>

```

**Comment by Super-Chama** [comment]
@vpanag I have fixed this issue in a different branch. https://github.com/orangehrm/oxd/pull/786/commits/9328fceaf61ede65f4dc0074ac92de0a0cba88fb

You will have to open an issue in https://github.com/orangehrm/orangehrm for this issue to be tracked by maintainers. OXD project is not currently tracking external issues.

**Comment by vpanag** [comment]
Thank you, opened https://github.com/orangehrm/orangehrm/issues/1876
